name: Docker Image CI

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

permissions:
  checks: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - id: cache-docker-restore
        name: Restore Docker Image
        uses: actions/cache/restore@v3
        with:
          key: ${{ runner.os }}-${{ hashFiles('/clox/Dockerfile') }}
          path: /var/lib/docker/

      - if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
        name: Build the Docker image
        run: docker build . --file Dockerfile --tag clox

      - id: cache-docker-save
        name: Save Docker Image
        uses: actions/cache/save@v3
        with:
          key: ${{ steps.cache-docker-restore.outputs.cache-primary-key }}
          path: /var/lib/docker/

      - name: Run tests in docker
        run: docker run --name=clox --mount type=bind,source=${PWD},target=/clox clox

      - if: always()
        name: Test Report
        uses: mikepenz/action-junit-report@v3.7.6
        with:
          report_paths: 'target/test_results.xml'
