name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag clox
      - name: Run tests in docker
        run: docker run --name=clox --mount type=bind,source=${PWD},target=/clox clox
      - name: Test Report
        uses: mikepenz/action-junit-report@v3.7.6
        if: success() || failure()
        with:
          report_paths: 'target/test_results.xml'
